gov:
  paperwork:
    auth-validation-url: http://management-service/v1/introspect

spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: management-service
          uri: lb://management-service
          predicates:
            - Path=/management/**
          filters:
            - RewritePath=/management/(?<path>.*), /$\{path}

        - id: applicants-service
          uri: lb://applicants-service
          predicates:
            - Path=/applicants/**
          filters:
            - name: AuthFilter
              args:
                allowed: /applicants/v1/register
            - RewritePath=/applicants/(?<path>.*), /$\{path}
